services:
  app:
    build: .
    container_name: sensortrack_app
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/sensortrack
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_NAME=sensortrack
      - DB_PASSWORD=postgres
    depends_on:
      - db
    networks:
      - st_network

  db:
    image: postgis/postgis:15-3.4
    container_name: sensortrack_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sensortrack
    volumes:
      - ./init/sql/create_tables.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - st_network

  adminer:
    image: adminer
    container_name: sensortrack_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - st_network

  nginx:
    image: nginx:stable-alpine
    container_name: sensortrack_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    depends_on:
      - app
      - adminer
    networks:
      - st_network

volumes:
  db_data:

networks:
  st_network:
    driver: bridge
